__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$


__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

__Решение №1__

Запишем расширенную матрицу системы:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1  \\ 
1 & 1 & -3 & 1 
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$


Путем элементарных преобразований постараемся привести матрицу к ступенчатому виду. (1) - (3): 

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1  \\ 
0 & 0 & 2 & -3 
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
-4
\end{matrix}
\end{pmatrix}.$$

Первую умножим на 2 и вычтем вторую

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & 1 & -1 & -5  \\ 
0 & 0 & 2 & -3 
\end{matrix}\right|
\begin{matrix}
0\\ 
2\\
-4
\end{matrix}
\end{pmatrix}.$$

Из второй вычесть первую

$$\begin{pmatrix}
\left.\begin{matrix}
-1 & 0 & 0 & -3 \\ 
0 & 1 & -1 & -5  \\ 
0 & 0 & 2 & -3 
\end{matrix}\right|
\begin{matrix}
2\\ 
2\\
-4
\end{matrix}
\end{pmatrix}.$$

вторую умножим на 2 и вычтем четвертую: 

$$\begin{pmatrix}
\left.\begin{matrix}
-1 & 0 & 0 & -3 \\ 
0 & 2 & -2 & -10  \\ 
0 & 0 & 2 & -3 
\end{matrix}\right|
\begin{matrix}
2\\ 
4\\
-4
\end{matrix}
\end{pmatrix}.$$

$$\begin{pmatrix}
\left.\begin{matrix}
-1 & 0 & 0 & -3 \\ 
0 & 2 & -2 & -10  \\ 
0 & 2 & 0 & -13 
\end{matrix}\right|
\begin{matrix}
2\\ 
4\\
0
\end{matrix}
\end{pmatrix}.$$

Получаем бесконечное множество решений. Запишем его в виде общего решения: 

$$2x_{2}=13x_{4} \; \Leftrightarrow \; x_{2}=13x_{4}/2,$$

$$-x_{1}=2+3x_{4} \; \Leftrightarrow \; x_{1}=-3x_{4}-2,$$

$$2x_{2}-2x_{3}-10x_{4}=4 \; \Leftrightarrow \; x_{3}=(3x_{4}-4)/2,$$

$$x_{4}=c,$$

__Решение №2__

Во примере _а)_ три неизвестных и три уравнения. В случае, __когда число уравнений равно числу неизвестных__ и матрица коэффициентов невырождена, если векторы столбцов коэффициентов $a_{1},a_{2},...,a_{n}$ линейно независимы, то такая система совместна, и ее решение единственно при любом векторе свободных членов $b$.

In [28]:
import numpy as np

In [29]:
a=np.array([[3,-1,1],
            [2,-5,-3], 
            [1,1,-1]])

In [30]:
det=np.linalg.det(a)

det

32.0

В примере _а)_ строки линейно независимы, следовательно, система совместна и имеет единственное решение. 

Рассмотрим пример _б)_. Три уравнения, три неизвестных. При этом вторая строка - это линейная комбинация первой и третьей строки. 

$$\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6 \\ 
1 & -2 & 3 \\ 
3 & -6 & 9
\end{matrix}\right|
\begin{matrix}
1\\ 
-2\\
-5
\end{matrix}
\end{pmatrix}.$$

Домножим вторую на три и вычтем третью строчку. Одновременно вторую строчку переместим на место первой, домножим ее на 2 и вычтем. 

$$\begin{pmatrix}
\left.\begin{matrix}
1 & -2 & 3 \\ 
0 & 0 & 0 \\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
-4\\ 
-5\\
1
\end{matrix}
\end{pmatrix}.$$

Как мы видим, свободные вектора линейно независимы и не являются линейной комбинацией строк. Система несовместна и решений не имеет. 

Рассмотрим пример _в)_. Здесь у нас три неизвестных и два уравнения. 

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5 \\ 
3 & 1 & -8 
\end{matrix}\right|
\begin{matrix}
4\\ 
-2
\end{matrix}
\end{pmatrix}.$$

Домножим первую строчку на 3 и вычтем из нее вторую. 

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5 \\ 
0 & 5 & 23 
\end{matrix}\right|
\begin{matrix}
4\\ 
14
\end{matrix}
\end{pmatrix}.$$

Система совместна и имеет бесконечное число решений. 

$$x_{3}=c,$$

$$5x_{2}+23x_{3}=14 \; \Leftrightarrow \; x_{2}=(14-23x_{3})/5 \; \Leftrightarrow \; x_{2}=(14-23с)/5,$$ 

$$x_{1}+2x_{2}+5x_{3}=4 \; \Leftrightarrow \; x_{1}=4+(-14+21с)/5 \; \Leftrightarrow \; x_{1}=(21с-8)/5,$$ 

__Решение №3__

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

n=4. Число неизвестных 

Причем:<br>
1) если $rankA=rank \tilde A=n$, где $n$ — число неизвестных, то система определена, т. е. имеет единственное решение;<br>

Уже сейчас видно, что в обоих матрицах нет линейно зависимых строк и столбцов. Давайте проверим это при помощи np.linalg.matrix_rank().

In [31]:
import numpy as np
a1=np.array([[1,3,-2,4],
             [0,5,0,1], 
             [0,0,3,0], 
             [0,0,0,2]])

a2=np.array([[1,3,-2,4,3],
             [0,5,0,1,2], 
             [0,0,3,0,4], 
             [0,0,0,2,1]])

rank_a1=np.linalg.matrix_rank(a1)
rank_a2=np.linalg.matrix_rank(a2)

print(f'ранг матриц: {rank_a1}')
print(f'ранг расширенной матрицы: {rank_a2}')

ранг матриц: 4
ранг расширенной матрицы: 4


Согласно теореме Кронекера-Копелли, система определена и имеет единственное решение. 

__Решение №4__

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Если $rankA<rank \tilde A$, то система несовместна.

In [32]:
a4=np.array([[1,2,3],
             [4,5,6], 
             [7,8,9]])

rank_a4=np.linalg.matrix_rank(a4)
rank_a4

2

Всего у нас три строки, три неизвестных, ранг матрицы равен двум, следовательно, строки являются линейно зависимыми. 

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
6 & 6 & 6\\ 
3 & 3 & 3\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
c-a\\ 
c-b\\
c
\end{matrix}
\end{pmatrix}.$$

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
0 & 0 & 0\\ 
3 & 3 & 3\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
c-2b+a\\ 
c-b\\
c
\end{matrix}
\end{pmatrix}.$$

Если $a-2b+c\neq 0$, то $rank \tilde A=3$, то система будет несовместной. 

In [34]:
a5=np.array([[1,2,3,1],
             [4,5,6,1], 
             [7,8,9,1]])

rank_a5=np.linalg.matrix_rank(a5)
rank_a5

2

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$
    
__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

__Решение №1__

In [39]:
a=np.array([[1,-2],
            [3,-4]])

a1=np.array([[1,-2],
             [7,-4]])

a2=np.array([[1,1],
             [3,7]])

deta=np.linalg.det(a)
deta1=np.linalg.det(a1)
deta2=np.linalg.det(a2)

In [40]:
print(f'x1={deta1/deta}')
print(f'x2={deta2/deta}')

x1=4.999999999999998
x2=1.9999999999999991


x1=5, x2=2

In [41]:
a=np.array([[2,-1,5],
            [1,1,-3],
            [2,4,1]])

a1=np.array([[10,-1,5],
             [-2,1,-3],
             [1,4,1]])

a2=np.array([[2,-10,5],
             [1,-2,-3],
             [2,1,1]])

a3=np.array([[2,-1,-10],
             [1,1,-2],
             [2,4,1]])

deta=np.linalg.det(a)
deta1=np.linalg.det(a1)
deta2=np.linalg.det(a2)
deta3=np.linalg.det(a3)

x1=deta1/deta
x2=deta2/deta
x3=deta3/deta

print(x1, x2, x3)

2.0000000000000018 2.255813953488373 0.0697674418604651


__Решение №2__

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$
    

In [44]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
import scipy.linalg

In [45]:
a=np.array([[1,2,4],
            [2,9,12],
            [3,26,30]])
P, L, U = scipy.linalg.lu(a)

In [46]:
print(P)
print(L)
print(U)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.8        1.        ]]
[[ 3.         26.         30.        ]
 [ 0.         -8.33333333 -8.        ]
 [ 0.          0.          0.4       ]]


In [48]:
b=np.array([[1,1,2,4],
            [2,5,8,9],
            [3,18,29,18],
            [4,22,53,33]])
P, L, U = scipy.linalg.lu(b)

In [49]:
print(P)
print(L)
print(U)

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.75       -0.25        1.          0.        ]
 [ 0.25        0.75       -0.17073171  1.        ]]
[[  4.          22.          53.          33.        ]
 [  0.          -6.         -18.5         -7.5       ]
 [  0.           0.         -15.375       -8.625     ]
 [  0.           0.           0.          -0.09756098]]


__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

In [50]:
A=np.array([[2,1,3],
            [11,7,5],
            [9,8,4]])

P,L,U = scipy.linalg.lu(A)

In [51]:
print(P)
print(L)
print(U)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[ 1.          0.          0.        ]
 [ 0.81818182  1.          0.        ]
 [ 0.18181818 -0.12        1.        ]]
[[11.          7.          5.        ]
 [ 0.          2.27272727 -0.09090909]
 [ 0.          0.          2.08      ]]


In [52]:
print(np.dot(P,A) - np.dot(L,U))

[[-2.  1. -1.]
 [-7. -7. -1.]
 [ 9.  6.  2.]]


In [53]:
B = np.array([1, -6, -5])
C = np.c_[A,B.T]
np.linalg.matrix_rank(A, .0001), np.linalg.matrix_rank(C, .0001)

(3, 3)

In [54]:
np.linalg.solve(A, B)

array([-1.,  0.,  1.])