## Практическое задание

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    
__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

## Решение

## №1

Матрицу $A$ можно умножить не на всякую матрицу $B$: __необходимо, чтобы число столбцов матрицы $A$ было равно числу строк матрицы $B$.__

Допустим, есть матрица $m\times n$ (A) и матрица B: $n\times k$. Произведение этих матриц = $m\times k$

- #1 Матрица A: 2 столбца. Матрица B: 4 строки. Матрица перемножить нельзя. 
- #2 Матрица A: 5 столбцов. Матрица B: 5 строк. Матрицы перемножить можно. Размер матрицы $m\times k$ = 2*3 = 6 

## №2

In [4]:
import numpy as np

In [5]:
a=np.array([[1,-2],[3,0]])
b=np.array([[4,-1],[0,5]])

In [6]:
print(f'Cумма матриц А + В: \n{a+b}')

Cумма матриц А + В: 
[[ 5 -3]
 [ 3  5]]


In [7]:
print(f'Умножение матриц А * В: \n{np.dot(a, b)}')

Умножение матриц А * В: 
[[  4 -11]
 [ 12  -3]]


## №3

In [8]:
a=np.array([[1,7],[3,-6]])
b=np.array([[0,5],[2,-1]])
c=np.array([[2, -4],[1,1]])

In [9]:
print(f'линейная комбинация 3а-2b+4c: \n{3*a-2*b+4*c}')

линейная комбинация 3а-2b+4c: 
[[ 11  -5]
 [  9 -12]]


## №4

In [10]:
a=np.array([[4,1],[5,-2], [2,3]])

In [11]:
b=a.T

In [12]:
c=np.dot(a,b)
c

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [13]:
d=np.dot(b,a)
d

array([[45,  0],
       [ 0, 14]])